"""Regenerate the custom Franka+Robotiq USD with the isaacsim6 mimic-damping fix.

The Robotiq 2F-85 mimic joints are underdamped in the flattened USD
(right_outer_knuckle dampingRatio=0) -> the passive finger linkage flails and the sim
diverges (NaN) once the arm moves. Set a stable dampingRatio + naturalFrequency on the
mimic joints so the linkage stays critically damped.

Output: franka_robotiq_2f_85_flattened_mimicfix.usd (referenced by robolab/robots/droid.py)
Run: python fix_robot_usd.py [dampingRatio=0.7] [naturalFreq=1000]

The committed .usd is generated by this script and is what droid.py loads; re-run only to
change the damping params. The OTHER isaacsim6 robot issue (the arm loading inverted) is
fixed separately in droid.py via init_state.rot, NOT here -- see the note by the save call.
"""
import os, shutil, sys
from pxr import Usd, Gf
import robolab.constants as c

src = os.path.join(c.ROBOTS_DIR, "franka_robotiq_2f_85_flattened.usd")
dst = os.path.join(c.ROBOTS_DIR, "franka_robotiq_2f_85_flattened_mimicfix.usd")
shutil.copy(src, dst)
st = Usd.Stage.Open(dst)
# Defaults are NOT from an upstream config (the flattened DROID USD is custom) -- they are
# the empirically-stable point for the 2F-85 mimic joints: dampingRatio=0.7 is standard
# near-critical damping (well-damped, no overshoot; the broken value was 0.0 = undamped ->
# NaN), naturalFrequency=1000 Hz is stiff enough that the passive linkage tracks the driven
# finger without lag. Overridable via argv to retune.
DAMP = float(sys.argv[1]) if len(sys.argv) > 1 else 0.7
NATFREQ = float(sys.argv[2]) if len(sys.argv) > 2 else 1000.0

# --- 1. mimic damping ---
mimic = 0
for p in st.Traverse():
    for a in p.GetAttributes():
        n = a.GetName()
        if n.startswith("physxMimicJoint:") and n.endswith(":dampingRatio"):
            a.Set(DAMP); mimic += 1
        if n.startswith("physxMimicJoint:") and n.endswith(":naturalFrequency"):
            a.Set(NATFREQ)

# NOTE: the flattened USD also loads the arm inverted (gripper starts below the workspace
# vs the pre-upgrade geometry). That is NOT fixed here -- rotating the baked link xforms
# doesn't help because the inversion lives in the articulation's joint frames. It is fixed
# at the config level in droid.py via init_state.rot=(0,0,0,1) (isaaclab3 reads the quat as
# xyzw, so that is the upright identity); verified load-bearing -- the wxyz identity
# (1,0,0,0) scores 0/6 on BananaInBowl & GrabAFruit vs 6/6 with (0,0,0,1).

st.GetRootLayer().Save()
print(f"mimic dampingRatio={DAMP} on {mimic} joints; wrote {dst}")
print("USDFIX_DONE")
